<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4km7wdw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4km7wdw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4km7wdw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4km7wdw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4km7wdw\appDevDebugProjectContainer([
    'container.build_hash' => '4km7wdw',
    'container.build_id' => '663f4b1e',
    'container.build_time' => 1591346887,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4km7wdw');
